/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.autoecole.frame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author Tun_Equip
 */
public class LoginGUI extends javax.swing.JFrame {
      int xMouse;
      int yMouse;
      Connection conn = null;
      ResultSet rs=null;
      PreparedStatement ps;
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        conn = ConnexionDB.Conection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        close = new javax.swing.JLabel();
        resize = new javax.swing.JLabel();
        MouveJFrame = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoecole/image/btn_finalPressed.gif"))); // NOI18N
        btn.setText("btn");
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMouseReleased(evt);
            }
        });
        getContentPane().add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 370, 310, 40));

        txtLogin.setBackground(new java.awt.Color(14, 142, 202));
        txtLogin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogin.setBorder(null);
        txtLogin.setCaretColor(new java.awt.Color(204, 204, 255));
        txtLogin.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtLogin.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtLoginMouseMoved(evt);
            }
        });
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLoginMouseExited(evt);
            }
        });
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 300, 30));

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoecole/frame/backtxt.png"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, 50));

        txtpassword.setBackground(new java.awt.Color(14, 142, 202));
        txtpassword.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(null);
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpassword.setSelectionColor(new java.awt.Color(255, 204, 204));
        txtpassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtpasswordMouseMoved(evt);
            }
        });
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtpasswordMouseExited(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 300, 40));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 30, 40));

        resize.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        resize.setForeground(new java.awt.Color(255, 255, 255));
        resize.setText("-");
        resize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resizeMouseClicked(evt);
            }
        });
        getContentPane().add(resize, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 30, 20));

        MouveJFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MouveJFrameMouseDragged(evt);
            }
        });
        MouveJFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MouveJFrameMousePressed(evt);
            }
        });
        getContentPane().add(MouveJFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        description.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        description.setForeground(new java.awt.Color(204, 0, 0));
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 470, 20));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoecole/image/LoginGUI001.gif"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        setSize(new java.awt.Dimension(497, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  @SuppressWarnings("unchecked")
    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        ImageIcon img=new ImageIcon(getClass().getResource("btn_finalHover.gif"));
        btn.setIcon(img);
    }//GEN-LAST:event_btnMouseEntered

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        ImageIcon img=new ImageIcon(getClass().getResource("btn_large.gif"));
        btn.setIcon(img);
    }//GEN-LAST:event_btnMouseExited

    private void btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMousePressed
        ImageIcon img=new ImageIcon(getClass().getResource("btn_finalPressed.gif"));
        btn.setIcon(img);
    }//GEN-LAST:event_btnMousePressed

    private void btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseReleased
        ImageIcon img=new ImageIcon(getClass().getResource("btn_finalHover.gif"));
        btn.setIcon(img);
    }//GEN-LAST:event_btnMouseReleased

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
         ImageIcon img=new ImageIcon(getClass().getResource("backtxt.png"));
         back.setIcon(img);
    }//GEN-LAST:event_txtLoginKeyPressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void resizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resizeMouseClicked
        this.setState(LoginGUI.ICONIFIED);
    }//GEN-LAST:event_resizeMouseClicked

    private void MouveJFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveJFrameMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse );
    }//GEN-LAST:event_MouveJFrameMouseDragged

    private void MouveJFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouveJFrameMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_MouveJFrameMousePressed

    private void txtLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseMoved
        description.setText("Entrer votre login pour accéder à votre session");
    }//GEN-LAST:event_txtLoginMouseMoved

    private void txtpasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseMoved
        description.setText("Entrer votre mot de passe pour accéder à votre session ");
    }//GEN-LAST:event_txtpasswordMouseMoved

    private void txtLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseExited
        description.setText("");
    }//GEN-LAST:event_txtLoginMouseExited

    private void txtpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseExited
        description.setText(" ");
    }//GEN-LAST:event_txtpasswordMouseExited

    private void btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseClicked
        String requette="select * from admin where login= ? and password=? ";
        try{
            ps=conn.prepareStatement(requette);
            ps.setString(1, txtLogin.getText());
            ps.setString(2, txtpassword.getText());
           rs= ps.executeQuery();
           if(rs.next()){
             
             dispose();
             new pageAceuilGui().setVisible(true);
             
           }
            
        }catch(Exception e){
			System.out.println("Exception" +e);
		}
        description.setForeground(Color.red);
          
        description.setText(" erreur");
        System.out.println(" login incorrect");   
	
    }//GEN-LAST:event_btnMouseClicked

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel MouveJFrame;
    private javax.swing.JLabel back;
    private javax.swing.JLabel btn;
    private javax.swing.JLabel close;
    private javax.swing.JLabel description;
    private javax.swing.JLabel resize;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
